name: one_spoon
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.2.0
  freezed_annotation: ^2.4.1
  freezed: ^2.4.7
  http: ^1.1.0
  flutter_screenutil: ^5.9.0
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.4.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
